name: Delete Published Maven Packages
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v1
        with:
          package-name: 'me.andidroid.test'
          num-old-versions-to-delete: 5
