# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Site

on: workflow_dispatch

jobs:
  site:
    name: Site Generation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Cache Maven packages
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-site-modules
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Site Generation
        run: mvn -B site site:stage
      - name: Site Upload
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          mvn -B scm-publish:publish-scm -s $GITHUB_WORKSPACE/settings.xml -Dscmpublish.skipCheckin=true
          cd target/scmpublish-checkout
          git add .
          git commit -m"update github pages with maven site"
          git push
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@v2
        with:
          name: site-artifact
          path: target/site/
